(in-package :mu-cl-resources)

(add-prefix "besluit" "http://data.vlaanderen.be/ns/besluit#")
(add-prefix "besluitvorming" "http://data.vlaanderen.be/ns/besluitvorming#")
(add-prefix "dbpedia" "http://dbpedia.org/ontology/")
(add-prefix "dct" "http://purl.org/dc/terms/")
(add-prefix "dossier" "https://data.vlaanderen.be/ns/dossier#")
(add-prefix "foaf" "http://xmlns.com/foaf/0.1/")
(add-prefix "generiek" "https://data.vlaanderen.be/ns/generiek#")
(add-prefix "mandaat" "http://data.vlaanderen.be/ns/mandaat#")
(add-prefix "nfo" "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#")
(add-prefix "nie" "http://www.semanticdesktop.org/ontologies/2007/01/19/nie#")
(add-prefix "org" "http://www.w3.org/ns/org#")
(add-prefix "person" "http://www.w3.org/ns/person#")
(add-prefix "persoon" "https://data.vlaanderen.be/ns/persoon#")
(add-prefix "prov" "http://www.w3.org/ns/prov#")
(add-prefix "rdf" "http://www.w3.org/1999/02/22-rdf-syntax-ns#")
(add-prefix "schema" "http://schema.org/")
(add-prefix "skos" "http://www.w3.org/2004/02/skos/core#")
(add-prefix "themis" "http://themis.vlaanderen.be/vocabularies/besluitvorming/")
(add-prefix "ext" "http://mu.semte.ch/vocabularies/ext/")